image: docker:latest
  

services:
  - docker:dind

before_script:
  - apk add npm bash git
  - npm install -g bats

test:
  script:
    - cp env-sample .env
    - cp config.production.json.sample config.production.json
    - ./up
    - bats tests
